blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.BlogView.as_view(), name='blog'),
    path('<int:blog_id>/comment', views.comment, name='comment'),
    path('api/<int:blog_id>', views.blog_endpoint, name='blog-endpoint-specific'),
    path('api/', views.blog_endpoint, name='blog-endpoint'),
]

changeTheWorld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('home.urls')),
    path('progress/', include('progress.urls')),
]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home")
]

progress/urls.py
from django.urls import path
from .views import index

app_name = 'progress'
urlpatterns = [
    path('', index, name='index'),
]

blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=200)
    description = models.TextField(max_length=20, default="no description")

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    author = models.CharField(max_length=200, default="unknown")
    content = models.TextField()

    def __str__(self):
        return self.content

progress/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.views import generic
from .models import BlogPost
from django.http import HttpResponseRedirect
from django.urls import reverse
# from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import BlogPostSerializer


class IndexView(generic.ListView):
    """
    the "browse page" for blog posts (should I rename it to that???)
    """
    template_name = 'blog/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        """fetches all posts"""
        return BlogPost.objects.order_by('-date_posted')


class BlogView(generic.DetailView):
    """
    the view that displays a blog post
    """
    model = BlogPost
    template_name = 'blog/blog.html'
    context_object_name = 'post'


@api_view(['GET'])
def blog_endpoint(req, blog_id=None):
    """
    the endpoint to blog posts, duh
    """
    print(blog_id)
    if blog_id is None:
        blogpost = BlogPost.objects.last()
        serializer = BlogPostSerializer(blogpost)
        return Response(serializer.data)

    blogpost = BlogPost.objects.get(pk=blog_id)
    serializer = BlogPostSerializer(blogpost)
    return Response(serializer.data)


def comment(req, blog_id):
    """
    where the form send the request when someone comments on a post
    """
    post = BlogPost.objects.get(id=blog_id)
    blog_comment = req.POST["comment"]
    author = req.POST["author"]
    post.comment_set.create(content=blog_comment, author=author)
    post.save()
    return HttpResponseRedirect(reverse('blog', args=[post.id]))

home/views.py
import requests
import json
from django.shortcuts import render

from changeTheWorld import settings


# Create your views here.


def home(request):
    members = requests.get("https://api.github.com/orgs/changetheeworld/members", headers={
        "Accept": "application/vnd.github.v3+json",
        "Authorization": "Bearer " + settings.GH_TOKEN,
        "X-GitHub-Api-Version": "2022-11-28"
    })

    return render(request, 'index.html', {'members': members.json()})

progress/views.py
from django.shortcuts import render
import requests

from changeTheWorld import settings


# Create your views here.


def index(request):
    repos = requests.get("https://api.github.com/orgs/changetheeworld/repos", headers={
        "Accept": "application/vnd.github.v3+json",
        "Authorization": "Bearer " + settings.GH_TOKEN,
        "X-GitHub-Api-Version": "2022-11-28"
    })
    print(repos.json())
    return render(request, 'progress/index.html', context={'repos': repos.json()})

templates/blog/blog.html
{% extends 'layout.html' %}
{% load static tailwind_tags %}
{% load humanize %}
{% block title %}
	<title>{{ post.title }} by {{ post.author|capfirst }}</title>
    <script type="module" src="https://md-block.verou.me/md-block.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

{% endblock %}

{% block content %}
	<body class="bg-black text-white ">
    <div class="flex justify-center md:pt-5 max-md:pt-10">
        <div class="w-[80ch]  min-h-screen">
            <div class="min-h-[70vh]">
                <p class="md:text-9xl text-5xl text-center mt-10 font-semibold">{{ post.title }}</p>
                <p class="md:text-3xl pl-10 pt-3 pb-5 text-white/70">by {{ post.author|capfirst }}, {{ post.date_posted|naturalday }}</p>
                <md-block>
                    {{ post.content }}
                </md-block>
            </div>

            <div class="bg-white/15 p-5 w-full h-min min-h-[calc(30vh_-_2.5rem)] rounded-t-2xl">
                <p class="font-bold pb-5">comments</p>
                <form action="{% url 'comment' post.id %}" method="post" class="sticky">
                    {% csrf_token %}
                    <fieldset class="bg-white/5 p-3 rounded-2xl ring-2 ring-white/10 flex flex-row">
                        <label class="max-md:w-full w-52 mr-3">
                            <input type="text" name="comment" class="bg-white/10 rounded-full outline-none py-2 w-full px-5 shadow-sm focus:bg-white/15" placeholder="comment" required>
                        </label>
                        <label class="max-md:w-full w-52 mr-3">
                            <input type="text" name="author" placeholder="username" class="bg-white/10 rounded-full w-full outline-none py-2 px-5 shadow-sm focus:bg-white/15">
                        </label>
                        <button value="comment" type="submit" class="bg-sky-500 p-2 rounded-full px-3 hover:bg-sky-400">submit</button>
                    </fieldset>
                </form>
                {% for comment in post.comment_set.all %}
                	<div class="py-3 hover:bg-white/10 pl-3 rounded-2xl">
                        <p class="text-white/70">{{ comment.author }}</p>
                        <p>{{ comment.content }}</p>
                   </div>
                {% endfor %}

            </div>
        </div>
    </div>
</body>

<style>
    md-block {
        font-size: 1rem;
        padding-left: .5rem;
        h1 {
            font-size: 2rem;
            padding-bottom: 10px;
            padding-top: 5px;
        }
        h2 {
            font-size: 1.75rem;
            padding-bottom: 5px;
            padding-top: 5px;

        }
        h3 {
            font-size: 1.5rem;
        }
    }
</style>
{% endblock %}

templates/blog/index.html
{% extends 'layout.html' %}

{% block title %}
   <title>the blog</title>
{% endblock %}

{% block content %}
	<body class="bg-black min-h-screen text-white">
        <div class="mt-10">
           <div class="flex flex-row max-md:flex-col">
            <div class="w-full h-full flex items-center md:min-h-screen max-md:min-h-24">
                <p class=" lg:text-9xl md:text-8xl font-semibold max-md:text-5xl text-center max-md:w-full md:pl-10">The Blog</p>
            </div>
            <div class="w-full h-full p-5">
                {% for post in posts %}
    {#            blog post #}
                <a href="{% url 'blog' post.id %}">
                    <div class="bg-gray-800 p-5 rounded-lg shadow-lg text-white my-5">
                        <p class="text-2xl">{{ post.title }} <span class="text-white/70">by {{ post.author|capfirst }}</span></p>
                        <p class="text-white/70 pt-1">{{ post.description }}</p>
                    </div>
                </a>
                {% endfor %}

                </div>
            </div>
        </div>
    </body>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
    <title>The Change The World Initiative</title>
{% endblock %}
{% block content %}
    <body class="bg-black text-white">
    <section id="home" class="w-screen h-screen flex flex-col">
        <div class="w-full h-full grid place-items-center">
            <div class="">
                <p class="font-bold text-7xl bg-clip-text text-transparent bg-gradient-to-t from-gray-100 to-75% to-slate-800 py-10 text-center">
                    Let's change the world together.</p>
                {#                TODO: change to something#}
                <p class="text-center text-gray-300 p-2">cuz why not lmao I have no idea what to put here, and I am to
                    lazy to put a lorem ipsum so read through that</p>
                <div class="grid place-items-center w-full h-min">
                    <div class="flex flex-row w-min justify-items-center items-center gap-3 mt-5">
                        <a href="https://github.com/ChangeTheeWorld"
                           class="home-button">GitHub</a>
                        <a href="{% url 'index' %}" class="home-button">Blog</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-full h-min bg-neutral-900 sm:px-3 pt-2">
            <p class="font-bold text-3xl max-sm:pl-3 pb-2">Our Team</p>
            <div class="h-24 flex flex-row gap-3 overflow-scroll pb-2">
                {% for member in members %}
                    <a href="{{ member.html_url }}" target="_blank">
                        <div class="w-full h-full max-sm:grid max-sm:place-items-center max-sm:w-screen">
                            <div class="h-full flex flex-row gap-2 p-2 hover:bg-white/10 rounded-xl w-min transition-all duration-75">
                                <div class="h-full aspect-square">
                                    <img src="{{ member.avatar_url }}" alt="{{ member.login }}'s profile picture"
                                         class="rounded-full">
                                </div>
                                <div class="w-full h-full grid place-items-center">
                                    <p class="m-auto">{{ member.login }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>

        </div>
    </section>
    </body>
{% endblock %}

templates/layout.html
{% load tailwind_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% tailwind_css %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0">
    {% block title %}
        <title>Title</title>
    {% endblock %}
</head>
<body>
    <div class="fixed p-3 top-0 w-screen h-min flex flex-row bg-black max-md:justify-center">
        <a href="{% url 'home' %}" class="layout-link">Change The World</a>
        <a href="{% url 'index' %}" class="layout-link">Blog</a>
        <a href="{% url 'progress:index' %}" class="layout-link">Progress</a>
        {#        <a href="javascript:alert('hello')" class="layout-link">lil button</a>#}
    </div>
    {% block content %}
    	<p>hello</p>
    {% endblock %}
</body>
</html>

templates/progress/index.html
{% extends 'layout.html' %}
{% block title %}
    <title>the progress</title>
{% endblock %}

{% block content %}
    <body class="bg-black text-white">
    <div class="mt-20">
        <p class="text-5xl pl-3 pt-3 font-bold">Progress</p>
        <div class="grid [grid-template-columns:_repeat(auto-fill,_minmax(15rem,_1fr));] gap-3 p-3">
            {% for repo in repos %}
                <div class="w-full bg-white/15 p-3 py-5 rounded-xl">
                    <p>{{ repo.name }}</p>
                    <p></p>
                </div>
            {% endfor %}
        </div>

    </div>
    </body>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>